### ISSUE TITLE
Provide real world example of GC file

### ISSUE THREAD

**Issue by andrewyatz** [tonyyzy/GC_analysis#5]
Provide an example of a wiggle file output generated from a real world sequence. Use s.cer and a small chromosome from UCSC as they already have this data available.

**Comment by tonyyzy** [comment]
@leannehaggerty I may need to add you to collaborators in order to assign this issue to you. But I can try to @ you for now?

**Comment by leannehaggerty** [comment]
Hey Tony

So I've done some digging and I think I've found what you need (honestly, I thought it'd be much easier to find).

Here (http://hgdownload.cse.ucsc.edu/goldenPath/hg19/gc5Base/) you will find the wiggle file hg19.gc5Base.txt. You'll see that this was created using hgGcPercent (window size of 5) from the input file hg19.2bit. You'll also see that this is for all the chromosomes from the human hg19 genome.

So what you want is the fasta input (rather than 2bit) and you want it only for one chromosome for now. 

My advice would be to extract the results for chromosome 1 from hg19.gc5Base.txt (that's your example wiggle output) and then go to here (http://hgdownload-test.cse.ucsc.edu/goldenPath/hg19/bigZips/) where you'll see that you can download chromFa.tar.gz, grab your chromosome 1 fasta file from there and bingo you have an example to work from.

That all sound ok? Let me know if you have any trouble, or if you find that this is not what you had in mind

Leanne

**Comment by tonyyzy** [comment]
Thank you Leanne, much appreciated.
