### ISSUE TITLE
Incorporate BioPython to check number of records in a fasta file

### ISSUE THREAD

**Issue by tonyyzy** [tonyyzy/GC_analysis#8]

**Comment by tonyyzy** [comment]
Currently, the program would exit and give a warning if more than one sequence is encountered. Therefore, only the first sequence is processed. I should have thought about the program's behavior more thoroughly.
If the fasta file contains, let's say, three sequences. And I want to save each sequence into a separate wiggle file. Do I ask the user to provide three output filenames? Or save according to the accession number? @leannehaggerty @andrewyatz

**Comment by leannehaggerty** [comment]
Sorry Tony, not sure how I missed this question.

I think in this situation you should perhaps take the user's output filename and append a unique and meaningful identifier (perhaps accession, like you said)

e.g. if user input was: _GC_analysis -i GRCh38.fasta -w 5 -s 5 -o GRCh38.wig_ 
and GRCh38.fasta contained 3 sequences I'd name the ouput:
_GRCh38_seq1.wig, GRCh38_seq2.wig, GRCh38_seq3.wig_

I would also recommend that you only ask for the output filename prefix from the user, i.e. GRCh38 (without .wig).
You should always ensure that the output has the correct extension instead of leaving it up to the user. If a user does provide GRCh38.wig then the output created would be called GRCh38.wig.wig, but that's fine, that's usual behaviour of this kind of program.

Hope this helps
